### ISSUE TITLE
Needing an authentication token for tests is not obvious

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/github-rs#112]
In #97 a possible contributor ran into an issue where the tests didn't run! This was because they didn't have a token from GitHub but that's completely non-obvious. This isn't a fun user experience either. There's two things that need to be done. 

1. [CONTRIBUTING.md](../blob/master/CONTRIBUTING.md) needs to be updated to include a section on testing and the need for an [auth token from GitHub](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) and that it needs to be put at `tests/auth_token` for the tests to run.
2. Any `unwrap()` call on the `auth_token()` function [like here](https://github.com/mgattozzi/github-rs/blob/master/tests/users.rs#L63) should be changed over to `expect()`, telling the user they need an authentication token in case they run the tests without looking at the docs at all.

**Comment by bryanjhv** [comment]
I'd like to take this one.
Which permissions are required for tests to run (so they can be specified in CONTRIBUTING)?

**Comment by akshatgoel** [comment]
@bryanjhv I have actually published a PR for this one (not sure why it is not showing as referenced here). You can review it [here](https://github.com/mgattozzi/github-rs/pull/113).

That being said, I am not sure why the build failed. Looks like an unrelated issue. Will wait for @mgattozzi  's comments.

**Comment by bryanjhv** [comment]
Ok, the only thing you're missing is the Rust part (`expect`) to notify users that need.

**Comment by mgattozzi** [comment]
I also just normally say all of them for mine but:
- public_repo
- repo:status
- read:user

At the minimum it seems, but I haven't tested this out though. this is just my guess based off the endpoints called.

**Comment by Dylan-DPC** [comment]
#113 solves this so we can close this issue.
