### ISSUE TITLE
workaround for not implemented APIs

### ISSUE THREAD

**Issue by jaroslaw-weber** [mgattozzi/github-rs#123]
There are currently APIs that are not implemented. It would be great to have some workaround for that until the API is implemented.

**Comment by jaroslaw-weber** [comment]
i found the custom endpoint. it would be great to have an example how to use it!

**Comment by mgattozzi** [comment]
Yeah this would be great! Would you like to submit an example to the examples folder? I'm thinking this is blocked on #124 but if you do that in one PR it would be awesome! Again totally willing to mentor and help you understand the codebase
