### ISSUE TITLE
add option to specify header

### ISSUE THREAD

**Issue by jaroslaw-weber** [mgattozzi/github-rs#124]
i am trying to use preview custom endpoint (reactions), but i get an error:

```
Some(Object({"documentation_url": String("https://developer.github.com/v3"), "message": String("If you would like to help us test the Reactions during its preview period, you must specify a custom media type in the \'Accept\' header. Please see the docs for full details.")}))
```

**Comment by mgattozzi** [comment]
Ah yeah that's true if you're using stuff that's being previewed you'll need some extra headers.

Really all that needs to be done is under `src/client.rs` add a `impl CustomQueryBuilder` block to add a function to allow mutating the header to a custom one. Would you like to submit a PR? I really need to go through the current ones but this shouldn't be too hard to do and I'd be willing to mentor on it.

**Comment by jaroslaw-weber** [comment]
I will try and send a PR later :)
