### ISSUE TITLE
rustls usage of ring blocks alternative platform support

### ISSUE THREAD

**Issue by xen0n** [mgattozzi/github-rs#133]
The most prominent dependency of `rustls` is `ring`; in its current form `ring` only supports the x86 and ARM platforms. As such minority architectures are broken and the upstream porting is unlikely in short-term.

As the crate shouldn't care about the actual TLS implementation, maybe the choice could be provided via `cfg` features. `native-tls` support would be decent but any configurable option would suffice.

**Comment by mgattozzi** [comment]
I'm definitely okay with this. I left comments on #134!
