### ISSUE TITLE
Pagination?

### ISSUE THREAD

**Issue by kunicmarko20** [mgattozzi/github-rs#162]
I am looking into this package and I don't see anything for pagination, meaning we aren't be able to fetch all the data, only the first page, am I correct? Also I see #159 and I assume the user meant to ask the same question.

https://developer.github.com/v3/guides/traversing-with-pagination/

**Comment by kunicmarko20** [comment]
Ended up implementing my own client and parsing pagination header with hyper https://github.com/kunicmarko20/ghnotifier-rs/blob/0347b6632605b48e06576b3aca7931605487d0d5/src/github_client.rs#L47-L61.

**Comment by BatmanAoD** [comment]
There is also an existing issue: #18
