### ISSUE TITLE
Support hidden API endpoints

### ISSUE THREAD

**Issue by mathstuf** [mgattozzi/github-rs#19]
So I contacted Github about one of the endpoints we'd need and apparently it exists, but is not publicly documented (though they did mention that it is stable and may become public in the future). Rather than exposing such an endpoint through a trait, it'd be nice to be able to craft a custom URL for use. This would probably just return a plain JSON value rather than trying to decode it as anything (though I guess it could be polymorphic over any `T: Deserialize`).

**Comment by mgattozzi** [comment]
I think that's doable. It could be a nice stop gap for people in the meantime while the rest of the API is still getting built into functions. I have an underlying JSON type in types.rs I think that's an alias to the HashMap that Serde uses to access values. It would be best to make generic functions for GET, PUT, DELETE, and POST. In the case of PUT and POST it'll need to be polymorphic over `T: Deserialize`

**Comment by mgattozzi** [comment]
I plan on adding a custom endpoint soonish that will allow flexibility for the API while things aren't complete. This should be easy to do now that the new design has been implemented

**Comment by mgattozzi** [comment]
Custom endpoints were added in #37!
