### ISSUE TITLE
docs are not there

### ISSUE THREAD

**Issue by matthiasbeyer** [mgattozzi/github-rs#33]
It seems that the docs are not there for the repository. The link leads to an empty doc page.

**Comment by mgattozzi** [comment]
docs.rs doesn't lead directly to it but I can see how this can be confusing and I can update the link if this helps you out. Here's the link to the actual [docs](https://docs.rs/github-rs/0.4.0/github_rs/github/index.html)! I am in the middle of completely rewriting the API so these docs will end up being irrelevant in the next release.

**Comment by matthiasbeyer** [comment]
Wow, awesome! Thanks a lot for your effort!

**Comment by mgattozzi** [comment]
@matthiasbeyer Thank you! If you run into any issues or have endpoints that you need prioritized please feel free to open up an issue and I'll be more than happy to get them working for the next release. It's blocked till Hyper v0.11 is out. I'll release a pre-release then until pub(restricted) gets stabilized!
