### ISSUE TITLE
Add compiletest

### ISSUE THREAD

**Issue by killercup** [mgattozzi/github-rs#45]
Add compile-fail tests to make sure invalid queries can't be constructed. You can also use it to make sure "good" errors are thrown, or warnings (e.g. from must_use) are present.

(Diesel is using this for testing the query builder if you want to see a non-compiler use case.)

**Comment by mgattozzi** [comment]
Given how Diesel works compared to this I'm not sure if that's possible. I'll see if it is though. I do want to build a test suite of requests anyways to make sure they all work and return correct values amongst other things.

**Comment by mgattozzi** [comment]
Ah okay I see what Diesel is doing. Yeah I'll add some in as part of a big test suite

**Comment by mgattozzi** [comment]
Currently we don't have a way to test invalid queries. We should set something up like Diesel does. You can see an example of the tests and code to get it to work [here](https://github.com/diesel-rs/diesel/tree/master/diesel_compile_tests).

Steps to complete:
1. Set up the testing crate by adding it to the workspace in Cargo.toml
2. Set up some tests of invalid compile queries (e.g. calling a function `id` for a type that doesn't have it)
3. Add as many tests as possible to cover a wide range. Note just getting the framework
    in place is enough to get this issue closed but having quite a few tests to go with it would be great.

**Comment by hdhoang** [comment]
That's a nice way to structure the tests. I'll switch #109 over to this method.

**Comment by mgattozzi** [comment]
@hdhoang nice thanks!
