### ISSUE TITLE
RFC: GitHub v4 and maintenance of v3

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/github-rs#52]
Today GitHub announced that they're moving over to GraphQl for their "v4" library. As such all of the bindings and code now are going to not work after sometime. When I wrote issue #2 I thought they would coexist for a while but at some point "v3" much like "v2" and "v1" will be deprecated. As such going forward it seems like making this a graph-ql library would make sense. However, I'd rather not just abandon support for v3 altogether and it looks like I'll need to create a graphql library anyways to send and receive queries. Most likely with something like serde. I'm leaving this open to hear people's opinions on the matter if they have any.

Given my limited time and the official announcement/longer term maintainability of a graphql library I propose the following:

- Split code for v3 into a separate workspace in the repo. PRs and such will still be accepted to maintain or extend it
- Start working on a v4 library in tree probably calling it github-graphql-rs
- As there is no graphql serialization/deserialization library I'll need to work on that crate first

Questions and concerns? Drop them below!

**Comment by mathstuf** [comment]
There have been mentions of folks working on GraphQL client libraries, but I've only seen questions, not actual repositories. There's the juniper GraphQL *server* in Rust, but I haven't seen a client library yet :( .

**Comment by mgattozzi** [comment]
Yeah @mathstuf this is what I've seen as well. The spec for GraphQL also doesn't map to Rust all to well from what I've done with [gql-rs](https://github.com//mgattozzi/gql-rs) though it has been some time since I even worked on it. All the code for it is still sitting on my machine. The nice thing is we only really need to worry about serialization and deserialization. What people do with it afterwards is up to them. This should make it a bit easier to work with at least. Still I'd like to see a client based library rather than a server one soon.

**Comment by mathstuf** [comment]
I feel like some build-time library to convert from a GraphQL IDL into Rust is probably best (though I can't seem to see where this IDL is specified?).

**Comment by mgattozzi** [comment]
You mean GitHub's IDL?

**Comment by mathstuf** [comment]
I see hints of there being some GraphQL IDL which describes the API (kind of like D-Bus XML if you're familiar with it).

**Comment by mgattozzi** [comment]
I have not messed with D-Bus XML personally. It'd be great to get the IDL if possible. The docs are a bit sparse at this point but I have made a few requests with curl to see how it works/if it does. For now I was thinking maybe allow querying by graphQL as a String input (for experimentation/using it) but later add a type safe serialization layer on top of it for people to use as docs become more available.

**Comment by mathstuf** [comment]
That would be a good start at least…I don't know what their timeline for removing v3 is and I'd rather not be hit with a "in two weeks" deadline :) .

**Comment by mgattozzi** [comment]
I've put in #84. github-rs is still the primarily supported crate but V4 is now getting work started with it.
