### ISSUE TITLE
Support GET parameters

### ISSUE THREAD

**Issue by AlexNPavel** [mgattozzi/github-rs#60]
Some parts of the v3 API have optional GET parameters, such as https://developer.github.com/v3/pulls/#list-pull-requests. These should probably be added to this library as they can provide useful functionality (like sorting pull requests by date).

**Comment by mgattozzi** [comment]
I've been thinking a bit about this. If you take a look at [this line](https://github.com/mgattozzi/github-rs/blob/a0de20fef6ddab3b6c0590995a669cde8712e400/src/client.rs#L122) this is how the get type is called. Not far bellow it you'll see we have both `put` and `put_empty`. Best thing to do would be to create a `GetWithQueryBuilder` type and have a function called `get_with` that takes in a list of parameters that are then passed in at the end for execution. More than happy to mentor this issue as I've been a bit busy with work and the new rustdoc rewrite.

**Comment by AlexNPavel** [comment]
If we do end up using reqwest instead of hyper like pull #64 suggests, this we could use reqwest's set_query function on the reqwest Url when first making the GetQueryBuilder, and then to preserve that when we expand the Url (in url_join), we could do something like this:
```
pub fn url_join(url: &Url, path: &str) -> Result<Url, UrlError> {
    match url.join(path) {
        Ok(new_url) => {
            new_url.set_query(url.query());
            url
        },
        Err(e) => Err(e),
    }
}
```
This makes it very simple, we would just need to decide how we want users to create the query without have to manually supply a string of the form `"state=closed&sort=popularity"`. A Hashmap could work for that.

**Comment by mgattozzi** [comment]
I think a HashSet would also serve that purpose well. It'll make sure we avoid people adding the same thing twice by accident. Unlikely but it makes sense design wise. HashSet is just a HashMap in Rust with some extra restrictions is all. Probably would do something like `HashSet<&str, &str>` with whatever lifetime parameters are needed. I think this would work out well!

**Comment by mgattozzi** [comment]
Support for this was added in https://github.com/mgattozzi/github-rs/commit/be41a90a16abf12c5e5d0ce0ff11eaecff994ba7 and works under version 0.6.0 so I'm closing this. @AlexNPavel I'm pinging you incase you didn't know :D
