### ISSUE TITLE
Hacktoberfest issues?

### ISSUE THREAD

**Issue by marioidival** [mgattozzi/github-rs#86]
Hey, you can add some labels in issues or create new issues with hacktoberfest labels?

**Comment by mgattozzi** [comment]
Yeah I'd love to actually. Let me whip some up tomorrow and leave instructions for people! Most of my work is being done on the upcoming V4 API but many people still use V3 (and it's better documented). Mostly it's adding endpoints which isn't all that hard! It just takes time! I'll get to it tomorrow before work. Does that sound good @marioidival?

**Comment by marioidival** [comment]
@mgattozzi yes! I'm already working on adding an new endpoint

**Comment by mgattozzi** [comment]
I've started opening up issues so as you see them feel free to work on them :) Even if I don't label an issue hacktoberfest feel free to take a crack at them :D
