### ISSUE TITLE
Non-Preview Gists Endpoints

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/github-rs#89]
See the endpoints doc for more details about what is open. The subsections for this correspond to the folders under `src`:
- [x] GET
- [x] POST
- [x] PATCH
- [x] PUT
- [x] DELETE

Sub-Issue of #28

**Comment by Henning-K** [comment]
I'd like to take this one.
Just to clarify, is each of the subsections supposed to be a PR or the whole list in one PR?

**Comment by mgattozzi** [comment]
Hey @Henning-K You can do as few or as many in the subsections as you like! I'd prefer smaller focused PRs which makes it easier to review. Think maybe 10 to 15 endpoints as the upper limit. The checklist is mostly here to check off when the whole section is done.

**Comment by mgattozzi** [comment]
Also let me know if the macros are confusing to figure out to implement them. #28 has some more info but ping me if you run into trouble.

**Comment by Henning-K** [comment]
I haven't read through https://github.com/mgattozzi/github-rs/blob/master/docs/design.md fully yet. When I'm done and there are questions I know where to ask, thanks.

**Comment by mgattozzi** [comment]
Awesome! :D Looking forward to a PR

**Comment by Henning-K** [comment]
When is the "|?>" notation for the macros supposed to be used?
I've not seen any of the endpoints using this syntax here yet.

**Comment by mgattozzi** [comment]
@Henning-K [here's an example of it being used](https://github.com/mgattozzi/github-rs/blob/734fc1ecb9acd3985ada21d34daf4d932fc19b6d/src/repos/get.rs#L55) it's to allow url parameters to be passed in! It was functionality added in https://github.com/mgattozzi/github-rs/commit/be41a90a16abf12c5e5d0ce0ff11eaecff994ba7. Some endpoints have optional Url parameters that people can add to modify behavior and it adds support for it via that syntax. Makes sense?

**Comment by Henning-K** [comment]
Huh, ok.
Little aside for the DELETE part of this:
When there are two different endpoints which use the same variable name at their ends but one url has more "steps" than the other can both have the same name in regards to new_type?

Meaning
/gists/:id
and
/gists/:gist_id/comments/:id

Can these both use some type like "ID" as the final part of the chain that gets then plugged into exec!() exactly once?

**Comment by mgattozzi** [comment]
The convention for type names is each url bit gets an uppercase. In the above example:

/gists/:id -> GistsId
/gists/:gist_id/comments/:id -> GistsGistIdCommentsId

This keeps it distinct. For the most part the user really shouldn't be looking at the types. I want to cover this in #63 somehow. Makes sense?

**Comment by Henning-K** [comment]
Oh, ok, that makes sense.
I'll change the files to reflect this.

**Comment by mgattozzi** [comment]
Awesome! If you can do that for all the PRs I can take a look at them later today :D

**Comment by Henning-K** [comment]
Are the names in the POST PR right?

**Comment by mgattozzi** [comment]
ID should be Id but yeah this is correct. They're namespaced so you can have:

`github_rs::gists::post::Gists` and `github_rs::gists::delete::Gists`

They're distinct types so they end up not conflicting! The types end up creating a Directed Acyclic Graph (DAG) so it works well. A brief example:

```
Client ----> GetRequest --> Users --> Get Types for Users
       |---> PutRequest --> Users --> Put Types for Users
       |---> PostRequest --> Users --> Post Types for Users
       |---> DeleteRequest --> Users --> Delete Types for Users
       |---> PatchRequest --> Users --> Patch Types for Users
```

This means users can only build a valid query and can't access endpoints that don't exist for that type of requests. Even if they have the same type name they exist in different places so their type name actually isn't the same!

**Comment by Henning-K** [comment]
So should I leave the names as the big compound words they are now or was my original approach to not add them up at each step in the chain correct after all?

(Sorry if I don't make sense, it's pretty late here right now)

**Comment by mgattozzi** [comment]
No keep them as the big compound words for the endpoints. Just don't worry if they're the same between post and put for instance!

**Comment by Henning-K** [comment]
Ah, *now* I see what you mean.

**Comment by mgattozzi** [comment]
Yay! :D
