### ISSUE TITLE
Non-Preview Notifications Endpoints

### ISSUE THREAD

**Issue by mgattozzi** [mgattozzi/github-rs#92]
See the endpoints doc for more details about what is open. The subsections for this correspond to the folders under `src`:
- [ ] GET
- [ ] POST
- [ ] PATCH
- [ ] PUT
- [ ] DELETE

Sub-Issue of #28

**Comment by arbuztw** [comment]
Hi! I was wondering if I could take this?

**Comment by ktomsic** [comment]
Do you mind if I work on this next?

**Comment by mgattozzi** [comment]
No one else has claimed any of this so go for it!

**Comment by akshatgoel** [comment]
@ktomsic Are you working on this? I am planning to pick this up.

**Comment by mgattozzi** [comment]
@akshatgoel There is a PR by @ktomsic in #108 for search but not notifications. I've been so busy with my National Guard/Civilian Job/Vacation that only now I'm getting around to PRs this week. Thanks for your patience!

**Comment by akshatgoel** [comment]
@mgattozzi Thanks for the response. Does that mean I can pick this one up?

**Comment by mgattozzi** [comment]
I'd say go for it. @ktomsic if you do want this still ping here. @akshatgoel start with implementing one of them like GET so if @ktomsic wants we can split them up amongst you!

**Comment by ktomsic** [comment]
I have code written for all the notification endpoints, just working on testing and cleaning it up.

**Comment by akshatgoel** [comment]
@ktomsic I had actually completed GET endpoints after @mgattozzi 's response. Since you claimed it first, I think your changes should be merged. I will pick something else :)

**Comment by Dylan-DPC** [comment]
@ktomsic any updates on this?
